name: fampay
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  firebase_core: ^3.8.1
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.2.1
  http: ^1.2.2
  iconsax: ^0.0.8
  intl: ^0.20.1
  shared_preferences: ^2.3.4
  shimmer: ^3.0.0
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

